### ISSUE TITLE
Manage relations: need help

### ISSUE THREAD

**Issue by achirkof** [hyperoslo/Sync#257] opened 2016-08-22 21:35 UTC
Hello!

I'm stuck on the moment to save data. I have a JSON like this:
```JSON
{ 
    "_id" : "4yCb6LwmqwM2gnyWA", 
    "workoutName" : "Test new training program", 
    "workoutDesc" : "<p>Description</p>", 
    "workoutExercises" : [
        {
            "_id" : "6JDa8DFBe8K6Kkguw", 
            "exerciseName" : "Exercise 1", 
            "exerciseDesc" : "Description exercise 1", 
            "mainMuscle" : "Biceps", 
            "mechanicsType" : "Pull"
        }, 
        {
            "_id" : "Lx5mZNG5iGRagmtS4", 
            "exerciseName" : "Exercise 2", 
            "exerciseDesc" : "Description exercise 2", 
            "mainMuscle" : "Abs", 
            "mechanicsType" : "crunch"
        }
    ]
}
```
and my model defined like this: one `workout` have many `exercises`
![db88282fb82c4852807ce20f42d17a08](https://cloud.githubusercontent.com/assets/1292136/17872438/b7e4ee38-68c8-11e6-9ee3-67d235f88f13.png)

I try to save data to CoreData like this:
```Swift
func fetchData(completion: fetchDataCompletion) {
        Alamofire.request(.GET, BASE_URL + API_URL + "workouts", parameters: nil, encoding: .URL, headers: nil).validate().responseJSON { (response) in
            let response = response.result.value as! [String: AnyObject]
            print(response["data"])
            Sync.changes(response["data"] as! [[String: AnyObject]], inEntityNamed: "Workout", dataStack: DATAStack(modelName: "smartworkout_rest"), completion: { (error) in
                completion(error)
            })
        }.resume()
    }
```
but as a result I have only `workout` record in CoreData and no records for `exercise`

![screenshot at aug 23 00-33-48](https://cloud.githubusercontent.com/assets/1292136/17872552/49a4caaa-68c9-11e6-909c-f763d7f404d7.png)

Probably I'm doing something wrong? Does `Sync` should manage dependency by self?

**Comment by 3lvis** [comment] 2016-08-22 21:41
Hi! It's because your primary key is `_id` instead of the default ones that can either be `id` or `remoteID`.

You can fix this by marking your `id` attribute as primary key and then change it's remote key to map to `_id`.

**Comment by 3lvis** [comment] 2016-08-22 21:43
<img width="828" alt="screen shot 2016-08-22 at 23 42 57" src="https://cloud.githubusercontent.com/assets/1088217/17872817/32cd7bda-68c2-11e6-90bd-3fcda250c26c.png">

**Comment by 3lvis** [comment] 2016-08-22 21:43
I hope this fixes your issue!

**Comment by 3lvis** [comment] 2016-08-22 21:47
wait, this is weird. I'll have a look.

**Comment by 3lvis** [comment] 2016-08-22 22:09
I was able to reproduce this.

**Comment by 3lvis** [comment] 2016-08-22 22:20
The bug is related to the relationship name `workoutExercises`. Instead of using it as is, is converting it to workoutexercises, so it's failing. I'll look for a fix for this, meanwhile you could `exercises` instead of `workoutExercises` until a better solution is posted.

**Comment by achirkof** [comment] 2016-08-23 09:05
Hi @3lvis !

> The bug is related to the relationship name workoutExercises. Instead of using it as is, is converting it to workoutexercises, so it's failing. I'll look for a fix for this, meanwhile you could exercises instead of workoutExercises until a better solution is posted.

Yes, you are right, this is a cause. And also, because I receive from server `exercise`s array named `workoutExercises`, I have to add `hyper.remoteKey` with value `workoutExercises` to my relation named `exercises`.
I don't sure if it is a bug, maybe you just need to add some instructions to documentation?

**Comment by 3lvis** [comment] 2016-08-23 09:19
I'm certain that this is a bug.

**Closed** 2016-08-23 21:03 UTC

**Comment by 3lvis** [comment] 2016-08-23 21:08
Fixed here, thanks a lot for posting this well described bug. All the information that you posted was very useful to find the issue.

You can find a new release that fixes this: https://github.com/hyperoslo/Sync/releases/tag/1.12.1

Have an awesome week.

**Comment by achirkof** [comment] 2016-08-24 07:59
Now it is working well! Thanks!
