### ISSUE TITLE
Migrating to Swift 3 [Help wanted]

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [hyperoslo/Sync#285] opened 2016-09-23 11:27 UTC
**Here is my CoreData model**
![screen shot 2016-09-23 at 4 37 05 pm](https://cloud.githubusercontent.com/assets/7369485/18783874/109ed8e4-81ac-11e6-8e94-bb606f0c36c3.png)

**for example JSON,**

![screen shot 2016-09-23 at 4 46 32 pm](https://cloud.githubusercontent.com/assets/7369485/18784088/55ec2950-81ad-11e6-895a-ca621b4dc1d5.png)

**Related code:**

`func getFilmographyDetailsFromServer(completion: @escaping (NSError?) -> Void) {
  
      
        networkManager.bypassAuthentication()
        let hitURL = Service.baseURL + Service.path.getFilmoGraphy
        networkManager.manager!.request(hitURL, method: .get, parameters: nil)
            .responseJSON { response in
                if let data = response.result.value {
                    let result =  data as! [String : AnyObject]
                    if result["filmography"] != nil {
                        print(result["filmography"])
                        guard let filmography = result["filmography"] else {
                            return
                        }
                        let filmoResult = filmography as! [Dictionary<String, AnyObject>]
                        Sync.changes(filmoResult, inEntityNamed: "FilmographyCD", dataStack: self.dataStack, completion: { (error) in
                            completion(error)
                        })
                    }
                } else {
                    self.spotLoadView?.stopAnimation()
                    self.spotLoadView?.isHidden = true
                    self.showAlert(title: "Oops!!", message: (response.result.error?.localizedDescription)!)
                }
        }
    }`

The same core data setup works fine without any issues in `Xcode 7 & Swift 2`
But in `Xcode 8 & Swift 3', it is crashing at this line,

**~/Pods/Sync/Source/NSManagedObject+Sync.swift**
`let localItems = localRelationship.value(forKey: entity.sync_localPrimaryKey()) as? NSSet ?? NSSet()`

**With crash log,**

> Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<FilmographyDetailsCD 0x6000000ba1c0> valueForUndefinedKey:]: the entity FilmographyDetailsCD is not key value coding-compliant for the key "category".'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000102c1834b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000106bd821e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000102c18299 -[NSException raise] + 9
	3   CoreData                            0x00000001027cf204 -[NSManagedObject valueForUndefinedKey:] + 308
	4   Foundation                          0x0000000106756d9e -[NSSet(NSKeyValueCoding) valueForKey:] + 417
	5   Sync                                0x00000001049f6798 _TFE4SyncCSo15NSManagedObject23sync_toManyRelationshipfTCSo25NSRelationshipDescription10dictionaryGVs10DictionarySSP__6parentGSqS0__18parentRelationshipGSqS1__9dataStackC9DATAStack9DATAStack10operationsVC10DATAFilter10DATAFilter9Operation_T_ + 12424
	6   Sync                                0x00000001049f225a _TFE4SyncCSo15NSManagedObject23sync_fillWithDictionaryfTGVs10DictionarySSP__6parentGSqS0__18parentRelationshipGSqCSo25NSRelationshipDescription_9dataStackC9DATAStack9DATAStack10operationsVC10DATAFilter10DATAFilter9Operation_T_ + 4090
	7   Sync                                0x0000000104a08bb6 _TFZFC4Sync4Sync7changesFTGSaGVs10DictionarySSP___13inEntityNamedSS9predicateGSqCSo11NSPredicate_6parentGSqCSo15NSManagedObject_18parentRelationshipGSqCSo25NSRelationshipDescription_9inContextCSo22NSManagedObjectContext9dataStackC9DATAStack9DATAStack10operationsVC10DATAFilter10DATAFilter9Operation10completionGSqFGSqCSo7NSError_T___T_U0_FTGS1_SSP__S3__T_ + 198
	8   DATAFilter                          0x0000000103b526d6 _TZFC10DATAFilter10DATAFilter7changesfTGSaGVs10DictionarySSP___13inEntityNamedSS9predicateGSqCSo11NSPredicate_10operationsVS0_9Operation15localPrimaryKeySS16remotePrimaryKeySS7contextCSo22NSManagedObjectContext8insertedFGS1_SSP__T_7updatedFTGS1_SSP__CSo15NSManagedObject_T__T_ + 7590
	9   Sync                                0x0000000104a0822e _TZFC4Sync4Sync7changesfTGSaGVs10DictionarySSP___13inEntityNamedSS9predicateGSqCSo11NSPredicate_6parentGSqCSo15NSManagedObject_18parentRelationshipGSqCSo25NSRelationshipDescription_9inContextCSo22NSManagedObjectContext9dataStackC9DATAStack9DATAStack10operationsVC10DATAFilter10DATAFilter9Operation10completionGSqFGSqCSo7NSError_T___T_ + 3022
	10  Sync                                0x0000000104a060a5 _TFZFC4Sync4Sync7changesFTGSaGVs10DictionarySSP___13inEntityNamedSS9predicateGSqCSo11NSPredicate_9dataStackC9DATAStack9DATAStack10operationsVC10DATAFilter10DATAFilter9Operation10completionGSqFGSqCSo7NSError_T___T_U_FCSo22NSManagedObjectContextT_ + 469
	11  Sync                                0x0000000104a0629f _TPA__TFZFC4Sync4Sync7changesFTGSaGVs10DictionarySSP___13inEntityNamedSS9predicateGSqCSo11NSPredicate_9dataStackC9DATAStack9DATAStack10operationsVC10DATAFilter10DATAFilter9Operation10completionGSqFGSqCSo7NSError_T___T_U_FCSo22NSManagedObjectContextT_ + 255
	12  DATAStack                           0x0000000103b804c3 _TFFC9DATAStack9DATAStack29performInNewBackgroundContextFFCSo22NSManagedObjectContextT_T_U_FT_T_ + 67
	13  DATAStack                           0x0000000103b80507 _TTRXFo___XFdCb___ + 39
	14  CoreData                            0x0000000102763db7 developerSubmittedBlockToNSManagedObjectContextPerform + 199
	15  libdispatch.dylib                   0x0000000107e050cd _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x0000000107de2e6b _dispatch_queue_serial_drain + 236
	17  libdispatch.dylib                   0x0000000107de3b9f _dispatch_queue_invoke + 1073
	18  libdispatch.dylib                   0x0000000107de407f _dispatch_queue_override_invoke + 683
	19  libdispatch.dylib                   0x0000000107de63b7 _dispatch_root_queue_drain + 720
	20  libdispatch.dylib                   0x0000000107de608b _dispatch_worker_thread3 + 123
	21  libsystem_pthread.dylib             0x00000001081ae4de _pthread_wqthread + 1129
	22  libsystem_pthread.dylib             0x00000001081ac341 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any help is much appreciated to get this fixed. Thanks!

**Comment by pwestrich** [comment] 2016-09-23 16:27
I think this might be similar to the problem I'm having in #280.

**Comment by 3lvis** [comment] 2016-09-24 17:59
Hi, 

I'll have a look.

**Comment by 3lvis** [comment] 2016-09-24 18:07
Thanks for reporting this bug, @AnnieNinaJoyceV. I was able to reproduce it. https://github.com/hyperoslo/Sync/pull/286

**Comment by 3lvis** [comment] 2016-09-24 18:08
@pwestrich Yeah, looks like they could be related.

**Comment by 3lvis** [comment] 2016-09-24 18:22
@AnnieNinaJoyceV I was able to reproduce, probably because I'm using `id` as primary key. What are your primary keys for this entities?

https://github.com/hyperoslo/Sync/pull/286

**Comment by AnnieNinaJoyceV** [comment] 2016-09-24 18:28
@3lvis thank you for having a look on this issue. The original response doesn't have 'id' included. Thus mine has `category` and `film` as primary keys.

**Comment by 3lvis** [comment] 2016-09-24 18:38
Hi @AnnieNinaJoyceV I'm having a hard time reproducing this bug. Seems to be working fine from here.

https://github.com/hyperoslo/Sync/pull/286

**Comment by 3lvis** [comment] 2016-09-24 18:39
Any ideas on what I could try to reproduce the crash?

**Comment by AnnieNinaJoyceV** [comment] 2016-09-24 18:41
@3lvis ah, I'm not sure.. Even it works for me if I use swift 2.3 branch. The live app uses 2.3 branch. Is there something I might have probably missed?

**Comment by AnnieNinaJoyceV** [comment] 2016-09-24 18:42
Or I will try to make a demo project and share by Monday?

**Comment by 3lvis** [comment] 2016-09-24 18:43
@AnnieNinaJoyceV I'll try to reproduce on the Swift 2.3 branch. If it works there as well, a demo project would be very useful.

Thanks for following up! Have a great weekend 🌻

**Comment by AnnieNinaJoyceV** [comment] 2016-09-24 18:45
Sure, great weekend to you too :)

**Comment by AnnieNinaJoyceV** [comment] 2016-09-26 07:44
Hi @3lvis I hope you had a great weekend. Here is a very rough demo project for this issue - https://www.dropbox.com/s/mcmrigrnczxh5ku/Sync285.zip?dl=0
Please let me know after checking :)

**Comment by 3lvis** [comment] 2016-09-26 16:46
Thanks for supplying the demo project. I used it to verify that this was fixed on the latest Sync release. 

# [Fixed on Sync 2.1.2](https://github.com/hyperoslo/Sync/releases/tag/2.1.2)

**Closed by 3lvis** 2016-09-26 16:46 UTC
Labels: bug, in-progress, needs-more-info
