### ISSUE TITLE
Update notification not fired

### ISSUE THREAD

**Issue by violabg** [hyperoslo/Sync#153] opened 2015-12-13 09:53 UTC
When I receive a new json I need to do some clean up on my local data. For each deleted object I need to delete files the a user could have download, and the same is true for each update, where I need to delete the previously downloaded files and set a property that marks the update status.
I'm kind of new to core data son I thought to use notification:

```swift
func changeNotification(notification: NSNotification) {
        let updatedObjects = notification.userInfo?[NSUpdatedObjectsKey]
        let deletedObjects = notification.userInfo?[NSDeletedObjectsKey]
        let insertedObjects = notification.userInfo?[NSInsertedObjectsKey]
        let refreshedObjects = notification.userInfo?[NSRefreshedObjectsKey]

        print("updatedObjects: \(updatedObjects)")
        print("deletedObjects: \(deletedObjects)")
        print("insertedObjects: \(insertedObjects)")
        print("refreshedObjects: \(refreshedObjects)")
    }
```

I don't know if there is a better place to do what I need to do.
the problem is that if an entity gets its properties updated, those are reflected by Sync to core data, but the updatedObjects event is not fired, while is working on deleted and inserted.

**Comment by 3lvis** [comment] 2015-12-13 14:26
Hi, I just tried [running the AppNet example](https://github.com/hyperoslo/Sync/tree/master/AppNet) and inserts, updates and deletes are working fine. Also getting the notifications works, too.

<img width="1175" alt="screen shot 2015-12-13 at 15 24 30" src="https://cloud.githubusercontent.com/assets/1088217/11767431/a6e457d2-a1ad-11e5-93f8-65682bc5470c.png">

**Comment by 3lvis** [comment] 2015-12-13 14:28
I'll close this since I'm not able to reproduce your error. Could you provide an screenshot of your Core Data model? And example of the used JSON(s)?

**Comment by violabg** [comment] 2015-12-13 15:13
I have used your AppNet example, only thing i did I saved a local copy of the json to test the changes manually

```json
{
    "meta": {
        "min_id": "57030525",
        "code": 200,
        "max_id": "57030547",
        "more": true
    },
    "data": [
        {
            "created_at": "2015-04-06T15:07:06Z",
            "text": "Hello World!",
            "id": "10",
            "user": {
                "username": "10albarjeel1",
                "created_at": "2015-03-28T13:01:31Z",
                "id": "1"
            }
    },
        {
            "created_at": "2015-04-06T15:07:06Z",
            "text": "20Hello World!",
            "id": "2",
            "user": {
                "username": "2albarjeel1",
                "created_at": "2015-03-28T13:01:31Z",
                "id": "2"
            }
    },
        {
            "created_at": "2015-04-06T15:07:06Z",
            "text": "3Hello World!",
            "id": "3",
            "user": {
                "username": "3albarjeel1",
                "created_at": "2015-03-28T13:01:31Z",
                "id": "3"
            }
    },
        {
            "created_at": "2015-04-06T15:07:06Z",
            "text": "4Hello World!",
            "id": "4",
            "user": {
                "username": "4albarjeel1",
                "created_at": "2015-03-28T13:01:31Z",
                "id": "4"
            }
    }
  ]
}
```

if I change the data text property, I see it on the ui (table view), but not updatedObjects is trigger.
Should't it count has an update?
Even on your screenshot the updatedObjects is nill

**Comment by 3lvis** [comment] 2015-12-13 15:20
Let me check :)

**Comment by 3lvis** [comment] 2015-12-13 16:22
Hi @violabg! Thanks for reporting this issue. Indeed, I'm not getting any notifications for updated objects. I'll have a look.

**Comment by 3lvis** [comment] 2015-12-13 16:25
@violabg Related to reacting to deleted elements, normally I would do it with something like [`DATASource`](https://github.com/3lvis/DATASource) where it has a delegate that tells you about deleted elements but might be nice to get something like that for Sync. I'll think about it. I have a similar use case and having that logic in Sync might be better than having it in DATASource which lives in the ViewController.

**Comment by violabg** [comment] 2015-12-13 16:29
ok, great

**Comment by 3lvis** [comment] 2015-12-13 17:05
There you go

https://github.com/hyperoslo/Sync/blob/master/AppNet/Networking.swift#L27-L57

**Closed by 3lvis** 2015-12-13 17:05 UTC

**Comment by 3lvis** [comment] 2015-12-13 17:18
<img width="918" alt="screen shot 2015-12-13 at 17 56 12" src="https://cloud.githubusercontent.com/assets/1088217/11768212/de51ae00-a1c5-11e5-995b-f912b1f87486.png">

**Comment by violabg** [comment] 2015-12-14 13:43
Hi 3lvis, I'm trying your new build with the local example, but now updatedObjects it is always dispatched even if you don't cache anything on the json

**Comment by 3lvis** [comment] 2015-12-14 13:59
@violabg > updatedObjects it is always dispatched even if you don't cache anything on the JSON.

I don't follow, could you explain, please?

**Comment by violabg** [comment] 2015-12-14 14:05
I have changed the code to use the local json:

```swift
func fetchNewData() {
        // Use the `networking.fetchLocalItems` method to try change notifications
        networking.fetchLocalItems { _ in
            self.fetchCurrentObjects()

            self.refreshControl?.endRefreshing()
        }
    }
```

now every time I run the up the console always print this: (no changes were made on the json)

<img width="882" alt="screen shot 2015-12-14 at 15 00 50" src="https://cloud.githubusercontent.com/assets/3963176/11782783/83a02974-a273-11e5-8b3b-914ed49ef5c0.png">

you can reproduce this by running the app many times

**Comment by 3lvis** [comment] 2015-12-14 14:20
@violabg that's how it works, it updates existing items.

**Comment by 3lvis** [comment] 2015-12-14 14:22
This is the code that checks if the value has changed before doing any updates, I guess it's not so smart for elements that have relationships.

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/blob/master/Source/NSManagedObject%2BHYPPropertyMapper.m#L33-L36

**Comment by violabg** [comment] 2015-12-14 14:25
but it does even if there are no changes

**Comment by violabg** [comment] 2015-12-14 14:28
what I see is that with the same json, no property or entities changes, just running the app many times, I get the screen shot above, where it prints updatedObjects, but it shouldn't since the data is the same.

**Comment by violabg** [comment] 2015-12-14 14:33
I debugged NSManagedObject+HYPPropertyMapper and non changes where found, but still get updatedObjects notification

**Comment by 3lvis** [comment] 2015-12-14 14:35
@violabg Made an issue for it :)

https://github.com/hyperoslo/Sync/issues/156

**Comment by 3lvis** [comment] 2015-12-14 15:23
Feel free to submit a fix :bouquet:

**Comment by violabg** [comment] 2015-12-14 16:26
I can confirm that this only happens to entities that have relationships

**Comment by 3lvis** [comment] 2015-12-14 18:36
@violabg Thanks! That helps :)

**Comment by 3lvis** [comment] 2016-01-14 17:26
Just submitted a fix for this

https://github.com/hyperoslo/Sync/pull/163
