### ISSUE TITLE
 -[NSLock unlock]: unlocked when not locked

### ISSUE THREAD

**Issue by Sorix** [hyperoslo/Sync#278] opened 2016-09-13 12:26 UTC
On application load sometimes I receive such errors in debug log. On application load I run Sync to sync from local Firebase to Core Data, it may run simultaneously several processes.

> 2016-09-13 11:45:45.677 *** -[NSLock unlock]: lock (<NSLock: 0x7f933c134aa0> '(null)') unlocked when not locked
> 2016-09-13 11:45:45.677 *** -[NSLock dealloc]: lock (<NSLock: 0x7f9339d6c180> '(null)') deallocated while still in use
> 2016-09-13 11:45:45.679 *** Break on _NSLockError() to debug.
> 2016-09-13 11:45:45.680 *** Break on _NSLockError() to debug.

![trace](https://cloud.githubusercontent.com/assets/5610904/18473534/900ee8f2-79ce-11e6-8068-e0d412c6a4f9.png)

**Comment by 3lvis** [comment] 2016-09-13 12:38
Oh, no, so you're getting crashes? In which version of Sync are you on?

**Comment by Proper-Job** [comment] 2016-09-13 12:58
@3lvis I see the same log message sometimes but I don't get crashes.

**Comment by 3lvis** [comment] 2016-09-13 13:00
@Proper-Job You're also using Firebase? 

Any pointers on how I can reproduce this? I don't have the same log. Xcode version? Swift version?

**Comment by Sorix** [comment] 2016-09-13 13:01
I don’t get crashes, but I’ve catched it in debugger as XCode suggested to show you trace. I will try to reproduce it in test project, but I think it won’t be an easy task :)

**Comment by pwestrich** [comment] 2016-09-14 18:06
I can confirm that this same error is present using Xcode 8.0 with Sync 2.0.0 in another project I'm working on. It seems all you have to do is call some variation of Sync.changes(...) to reproduce it. I'm having difficulty getting the debugger to break at _NSLockError() at the moment, so unfortunately I can't say for sure yet.

**Comment by 3lvis** [comment] 2016-09-14 20:24
Do you run Sync multiple entities at the same time? Maybe that's causing issues with the lock, since things are locked in one thread and unlocked in another one.

**Comment by pwestrich** [comment] 2016-09-14 20:26
I do have two calls to Sync one shortly after another. I believe Sync does make use of GCD to do some work, so perhaps that's causing the issue? I'm not near my development machine right now, so I can't try to disable the second call. I'll get to it tomorrow morning and let you know.

**Comment by 3lvis** [comment] 2016-09-14 20:32
The locks are located here, btw. 

https://github.com/hyperoslo/NSString-HYPNetworking/blob/master/Source/NSString%2BHYPNetworking.m#L69-L87

I use a singleton to store old versions of your remoteKeys to localKeys to improve performance.

**Comment by 3lvis** [comment] 2016-09-14 20:33
I needs the locks because NSDictionary is not thread safe.

**Comment by pwestrich** [comment] 2016-09-15 14:40
It appears the warning about the lock only shows up sometimes whenever I have both my calls to Sync in my program, but when I remove one of them, it consistently doesn't show up.

From what I can read in the documentation about NSLock, the second thread wanting the lock should park until the first one has released it, and the lock should live as long as the singleton who olds it, which is the duration of the program. I don't understand how either of the messages are popping up.

**Comment by pwestrich** [comment] 2016-09-15 14:55
Perhaps the guide [here](https://developer.apple.com/library/content/documentation/General/Conceptual/ConcurrencyProgrammingGuide/ThreadMigration/ThreadMigration.html#//apple_ref/doc/uid/TP40008091-CH105-SW3) coulee be of help? It seems Apple is discouraging the use of traditional threads and locks these days. Similar locking behavior could be accomplished by making a serial dispatch queue and making calls to `dispatch_sync()` to make sure they're done synchronously.

**Comment by 3lvis** [comment] 2016-09-15 19:14
@pwestrich interesting :) thanks! I think that confirms what the issue is.

**Comment by pwestrich** [comment] 2016-09-22 15:46
I just submitted a pull request on the other repository that implements this.
I had some free time, so seeing as you're so busy and I use this project a ton, figured why not.

**Comment by 3lvis** [comment] 2016-09-22 15:47
https://github.com/hyperoslo/NSString-HYPNetworking/pull/16

**Comment by 3lvis** [comment] 2016-09-22 15:47
@pwestrich thanks a lot!

**Comment by 3lvis** [comment] 2016-09-22 20:06
# BOOM! Fixed in 2.1.0

https://github.com/hyperoslo/Sync/releases/tag/2.1.0

**Closed by 3lvis** 2016-09-22 20:06 UTC
